nome = input('Qual é o seu nome completo? ')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
nomedividido = nome.split()
print('Seu primeiro nome tem {} letras'.format(len(nomedividido[0])))